# Configuration
# --------------------------------------

source $HOME/.zsh/config/variables.zsh
source $HOME/.zsh/config/aliases.zsh
source $HOME/.zsh/config/function.zsh

plugins=(git)
source $ZSH/oh-my-zsh.sh
